### ISSUE TITLE
Error - Secret store is not configured

### ISSUE THREAD

**Issue by marinaurena** [EdwinVW/dapr-hands-on#1]
Hi Edwin, how are you?

I followed the lab instructions step by step successfully but in assignment 05  I got the following error when I ran the TrafficControlService:  

_**Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="secret store is not configured".**_

I double-checked the lab and I'm sure I didn't miss a single step. I tried the Final folder and it gives me the same error.

Do you have any idea what could be happening?
Thanks in advance!

Marina

![console](https://user-images.githubusercontent.com/62021069/102652018-35bf9500-414c-11eb-838f-6a62176c3423.PNG)
![vs](https://user-images.githubusercontent.com/62021069/102652103-525bcd00-414c-11eb-94f3-237bd0c3d2b4.PNG)

**Comment by EdwinVW** [comment]
Hi @marinaurena,

This is a bug in the assignment (and the final solution). The name of the local file secret management component has been changed. I've updated the step-by-step instructons and the final solution in commit 472d516.

Please pull the latest version of the repo and try again. 

Thanks for creating this issue!

**Comment by marinaurena** [comment]
Hi Edwin,

Thank you very much for the quick response!

I pulled the latest version and it is working perfectly.

Thanks a lot! :)
